# Generated by Django 3.1.4 on 2020-12-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('dependants', models.IntegerField()),
                ('applicantincome', models.IntegerField()),
                ('coApplicantincome', models.IntegerField()),
                ('loanAmt', models.IntegerField()),
                ('loanTerm', models.IntegerField()),
                ('credithistory', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('graduateEducation', models.CharField(choices=[('Graduate', 'Graduated'), ('Not_Graduate', 'Not_Graduate')], max_length=15)),
                ('selfEmployed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('area', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=15)),
            ],
        ),
    ]
